version: "3.7"

services:
  mysql:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/sql:/sql
      - ./db/data:/var/lib/mysql
    container_name: mysql
    restart: always
    ports:
      - 127.0.0.1:33060:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
